### ISSUE TITLE
sending zip as attachment does not work

### ISSUE THREAD

**Issue by akhiljns** [peter-evans/sendgrid-action#6]
i have zipped a folder and trying to send it across via sendgrid but i do not receive any mail, but when i remove the attachment then i start receiving mails

below is the code i've written to send the mail

```
#! /usr/bin/env node

const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
    
const fs = require('fs');

const fileType = 'application/zip';

const pathToIndex = `${__dirname}/../reports.zip`;
const attachmentIndex = fs.readFileSync(pathToIndex).toString("base64");
    
const msg = {
    to: process.env.TO_EMAIL,
    from: process.env.FROM_EMAIL,
    subject: 'Jmeter Stress test report',
    text: 'Please find the JMeter test report attached.',
    html: '<p>Please find the JMeter test report attached.</p>',
    attachments: [
        {
            content: attachmentIndex,
            filename: "reports.zip",
            type: fileType,
            disposition: 'attachment',
        },
    ],
};
    
sgMail
.send(msg)
.then(() => console.log('Mail sent successfully'))
.catch(error => console.log(error.toString()));
```

and below is how i have zipped my folder

```
name: Run Stress Test

on:
  workflow_dispatch:

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: stress_test_components/stress.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: Create zip of reports folder
        run: zip -r reports.zip reports

      - name: list
        run: ls

      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1
        env:
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            TO_EMAIL: ${{ vars.TO_EMAIL }}
            FROM_EMAIL: ${{ vars.FROM_EMAIL }}
```

i have tried sending html document and it works fine, the problem seems to be with zip files

can you please help me figure out if i'm doing something wrong

also, i have made sure that my gmail receives mail with .zip files
